### ISSUE TITLE
Where is the project template?

### ISSUE THREAD

**Issue by thecristen** [JoshData/hackathon.guide#8]
Hi @JoshData! Great guide.

Twice in the document it mentions "refer to the project template given earlier"... but I can't find it! Is it the list under cultivating good projects? Is it somewhere else? There's no section identified as a "project template," as far as I can tell. Oversight?

**Comment by JoshData** [comment]
Ooops I deleted that in an earlier edit. I've revised it to point to the section Cultivating Good Projects which replaced that part. Thanks.
